DELETE FROM SCHEMA.USER_FILMORATE;
DELETE FROM SCHEMA.USER_FRIENDS;
DELETE FROM SCHEMA.FILM_LIKES;
DELETE FROM SCHEMA.FILM;
DELETE FROM SCHEMA.GENRE;
DELETE FROM SCHEMA.FILM_GENRE;
DELETE FROM SCHEMA.RATING;
