INSERT INTO RATING (RATING_ID, RATING_NAME)
values (1, 'G');
INSERT INTO RATING (RATING_ID, RATING_NAME)
values (2, 'PG');
INSERT INTO RATING (RATING_ID, RATING_NAME)
values (3, 'PG-13');
INSERT INTO RATING (RATING_ID, RATING_NAME)
values (4, 'R');
INSERT INTO RATING (RATING_ID, RATING_NAME)
values (5, 'NC-17');
INSERT INTO GENRE (ID, NAME)
values (1, 'Комедия');
INSERT INTO GENRE (ID, NAME)
values (2, 'Драма');
INSERT INTO GENRE (ID, NAME)
values (3, 'Мультфильм');
INSERT INTO GENRE (ID, NAME)
values (4, 'Триллер');
INSERT INTO GENRE (ID, NAME)
values (5, 'Документальный');
INSERT INTO GENRE (ID, NAME)
values (6, 'Боевик');
